language: cpp

jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      script:
        - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake -D ENABLE_COVERAGE:BOOL=ON .
        - cmake --build . -- -j2
        - ctest -j2
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-9
        - ls -R
    
    - os: windows
      before_script:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        # - ls "/c/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/Tools"
        
        # second way (longer)
        # - choco install visualstudio2019community
        # - choco install visualstudio2019-workload-nativedesktop
        # - export VS160COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools"
        # - ls "/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools"
      script:
        - cmake .
        - cmake --build .
        - ctest
