language: cpp

jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      script:
        - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake .
        - cmake --build . -- -j2
    
    - os: windows
      before_script:
        #- choco install visualstudio2019buildtools
        - choco install visualstudio2019community
        - export VS160COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools"
      script:
        - cmake .
        - cmake --build .
