language: cpp

jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      script:
        - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake .
        - cmake --build . -- -j2
    
    - os: windows
      before_script:
        - choco install visualstudio2019buildtools
        - msbuild.exe //version
        - where msbuild.exe
      script:
        - cmake .
        - cmake --build .
