image:
  - Visual Studio 2019
clone_folder: c:\project\source
build_script:
  - cmd: |-
     mkdir build
     cd build
     cmake c:\project\source -G "Visual Studio 16 2019"
     cmake --build . --config "Debug"
